### ISSUE TITLE
Resize firefox windows black line

### ISSUE THREAD

**Issue by pepib** [wmutils/core#24]
![wmutils](https://cloud.githubusercontent.com/assets/6834053/9713958/06ae628e-5555-11e5-9900-9dba38690fb5.png)
First of all thank you for this bundle of utils. My current configuration is XFCE+Openbox. I have problem related to resize if I try to resize somqe applications, e.g.  Firefox or Thunar, the side where I want apply the resize appear a black line? Where is problem?

**Comment by z3bratabs** [comment]
wmutils can't play well with reparenting window managers like openbox. Because
they create windows for the border, and make the applications sit within these
windows. This is a design wmutils can't handle, as it's meant to act on windows
directly. Also, openbox is EWMH compliant, which means it will expect
application to send EWMH request to change windows attributes, which wmutils
won't do. If you want a way to hack around openbox, you should give
[wmctrl](http://www.freedesktop.org/wiki/Software/wmctrl/) a go. It basically
works like wmutils, but it will send EWMH request to an already running WM,
rather than acting on the windows itself.
