### ISSUE TITLE
Negative numbers are seen as switches.

### ISSUE THREAD

**Issue by Faalentijn** [wmutils/core#41]
I noticed while using `wmp` that negative numbers on the left side of the command causes wmp to pick them up as switches rather than as numbers.

You can reproduce it by using the following command `wmp -r -100 0` which will print he usage message instead of moving to the cursor left.

I tested this on using latest commit with swm running.

**Comment by z3bratabs** [comment]
Valentijn wrote:
> I noticed while using `wmp` that using negative numbers on the left side of the command causes wmp to pick them up as argument switches rather than as numbers.
> 
> You can reproduce it by using the following command `wmp -r -100 0` and observe that it prints the usage message instead of moving the cursor left.
> 
> I tested this on using latest commit with swm running.

This is because numbers are valid characters for arg.h. You can easily get
around it by using the special flag "--", which means that argument list stops
there:

    wmp -r -- -100 0

arg.h is a file I copied elsewhere which is supposed to be a drop in solution
for argument parsing. I'd rather keep it untouched as it is working as expected
(numbers are valid characters for command line switches).

**Comment by z3bratabs** [comment]
The example in the manpage is wrong, though.

**Comment by Faalentijn** [comment]
Thanks for replying, I assumed that it wasn't expected behaviour because of the example in the man page.

**Comment by z3bratabs** [comment]
Fixed per commit adc455e
