### ISSUE TITLE
chwso doesn't appear to work

### ISSUE THREAD

**Issue by JonathanReeve** [wmutils/core#44]
I noticed this while trying to fix focus.sh in contrib. Focus.sh uses wtf and chwso to focus a window, but only wtf is working, so the window becomes focused, but is still behind other windows. Running chwso manually given a wid does nothing, and returns nothing. 

Tested on Arch Linux running GNOME.

**Comment by wildefyr** [comment]
wmutils isn't EWMH compliant. Don't expect it to work within an environment such as GNOME or i3 that implements EWMH as far as I understand, EWMH can vary heavily in implementation and is beyond the scope of this project.

**Comment by z3bratabs** [comment]
`wmutils`'s goal is to provide a full environment for someone to build their own way to manage X windows. The fact it *can* be used to extend existing window managers is a side effect. In this special case, there are chances that `wmutils` and `mutter` (if that's still Gnome's WM), are in conflict, both trying to take control over windows, which might be why `wmutils` appears to not work properly.

In order to  "extend" and existing EWMH compliant window manager, I'd suggest using `wmctrl` instead. Whose purpose is to talk directly to the WM, rather than trying to bypass it.
