### ISSUE TITLE
Wayland port?

### ISSUE THREAD

**Issue by Anachron** [wmutils/core#46]
I've just come across this project and I really love what you did here!
I'm wondering whether it can/will be ported to Wayland though,- did you dig into the specifications yet?

My idea is here to get the same workflow with the same script names, just the scripts itself have a different implementation.

This way one could replace his X-Server with Wayland and still have a fully working WM environment.

**Comment by z3bratabs** [comment]
From what I understand from wayland, it is not possible to "port" `wmutils` to it. Due to wayland's design, it is not possible to use it without having a full compositor running, that would handle everything frol drawing windows to managing the clipboard. `wmutils` provides binaries around builtin X features, like moving a window on the screen by making call to the *X server*, which is running for every session. There is no such thing in wayland, as the "compositor" (synonym to "window manager" for X), act as the server itself.

**Comment by Anachron** [comment]
Thanks for your quick response. But even then, would an api/interface not allow one to connect to this server and give commands to it?

**Comment by z3bratabs** [comment]
To make it "work", you would have to write a full compositor, and have it listen to different commands on a socket. Basically, something like `ratpoison`. This is totally different from `wmutils`' design. Another idea would be to take an existing conpositor with an external API, and send commands to it. This is, again, different from our design and closer to what `wmctrl` is.

`wmutils` is a set of standalone tools one can use to manipulate windows without needing a full WM.

**Comment by onodera-punpun** [comment]
>But even then, would an api/interface not allow one to connect to this server and give commands to it

The smart people behind Wayland didn't think of creating a standardized API. I'm sure there a few third part projects going on, but even then essential tools people use with wmutils, like a hotkey daemon, screenshot program, notification popup program etc. etc. can't, because all that stuff depends on the compositor.

**Comment by Anachron** [comment]
> The smart people behind Wayland didn't think of creating a standardized API. I'm sure there a few third part projects going on, but even then essential tools people use with wmutils, like a hotkey daemon, screenshot program, notification popup program etc. etc. can't be used, because all that stuff depends on the compositor.

Closing this as useless then. The more I hear about Wayland the more I doubt it will ever become a standard. Thanks for your great replies!
